### ISSUE TITLE
Changed course schema

### ISSUE THREAD

**Issue by ShirleyNekoDev** [HPI-de/hpi-cloud-apis#50]
**Description**

- missing fields:
  - [x] enrollmentDeadline
  - [x] attendance
- field "types" can contain:
  - [x] LECTURE
  - [x] SEMINAR
  - [x] PROJECT
  - [x] EXERCISE
  - [x] BLOCK_SEMINAR
- field "mandatory" should be an enum supporting the following values:
  - [x] bridge module
  - [x] compulsory module
  - [x] non-compulsory module
- fields, that can be null:
  - [x] requirements
  - [x] learning
  - [x] description
  - [x] examination
  - [x] dates
  - [x] literature

**Comment by JonasWanke** [comment]
Please use English for communication
